FROM quay.io/fedora/fedora:43

WORKDIR /

ARG istio_version

# Install ztunnel.
ARG TARGETARCH
COPY ${TARGETARCH:-amd64}/ztunnel /usr/local/bin/ztunnel

# Environment variable indicating the exact build, for debugging
ENV ISTIO_META_ISTIO_VERSION=$istio_version

ENTRYPOINT ["/usr/local/bin/ztunnel"]
